[package]
name = "sophie"
version = "0.1.0"
authors = ["Joshua Thayer <jthayer@mit.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.2.1"
num-traits = "0.2"
num-derive = "0.3"
radix_trie = "0.1.6"
